language: python
matrix:
  include:
    - python: "3.3"
    - python: "3.4"
    - python: "3.5"
    - python: "3.5-dev"
    - python: "3.6-dev"
    - python: "3.6"
    - python: "3.7-dev"
      dist: xenial
      sudo: true
    - python: "3.7"
      dist: xenial
      sudo: true
    - python: "3.8"
      dist: xenial
      sudo: true

# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - make coverage-xml
after_success:
  - codecov