language: python
cache:
  directories:
  - "$HOME/.cache/pip"
  - "$HOME/.pyenv"
matrix:
  include:
  - os: linux
    dist: trusty
    sudo: false
    python: '3.3'
  - os: linux
    dist: trusty
    sudo: false
    python: '3.4'
  - os: linux
    dist: trusty
    sudo: false
    python: '3.5-dev'
  - os: linux
    dist: trusty
    sudo: false
    python: '3.5'
  - os: linux
    dist: trusty
    sudo: false
    python: '3.6-dev'
  - os: linux
    dist: trusty
    sudo: false
    python: '3.6'
  - os: linux
    dist: xenial
    sudo: required
    python: '3.7-dev'
  - os: linux
    dist: xenial
    sudo: required
    python: '3.7'
  - os: linux
    dist: xenial
    sudo: required
    python: '3.8-dev'
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - make coverage-xml
after_success:
  - codecov